database:
  catalog: 'skotani_var'
  schema: 'var_app'
  tables:
    portfolio: 'portfolio'
    stocks: 'market_data'
    indicators: 'market_indicators'
    stock_returns: 'stock_returns'
    indicator_returns: 'indicator_returns'
    model_weights: 'model_weights'
    mc_portfolio_returns: 'mc_portfolio_returns'
    var_timeseries: 'var_timeseries'
    var_by_country: 'var_by_country'
    compliance: 'compliance_backtest'

model:
  name: 'value_at_risk'
  date: '2026-04-01'

yfinance:
  mindate: '2024-05-01'
  maxdate: '2026-05-01'

monte-carlo:
  executors: 20
  volatility: 90
  runs: 32000
