command:
  - uvicorn
  - main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"
env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "e9b34f7a2e4b0561"
  - name: MLFLOW_ENABLE_DB_SDK
    value: "true"
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
